services:
  backend:
    build: ./backend
    container_name: appfinanzas_backend
    restart: unless-stopped
    ports:
      - "8081:8081" # Coincide con server.port=8081 en tu .properties
    environment:
      # Datos extraídos de tu configuración de Render
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d7shkc37uimc73dpimvg-a.ohio-postgres.render.com:5432/appfinanzas_db_q1li?sslmode=require
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: YeyiNt6qwMDRzSV3E1Cc1WcOwU65cqRU
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 8081
    volumes:
      - ./volumes/backend/logs:/app/logs
    networks:
      - appfinanzas-network

  frontend:
    build:
      context: ./frontend
      args:
        # Ahora el frontend debe apuntar al puerto 8081
        VITE_API_URL: http://localhost:8081
    container_name: appfinanzas_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - appfinanzas-network

networks:
  appfinanzas-network:
    driver: bridge