spring.datasource.url=jdbc:postgresql://dpg-d7shkc37uimc73dpimvg-a.ohio-postgres.render.com:5432/appfinanzas_db_q1li?sslmode=require
spring.datasource.username=appuser
spring.datasource.password=YeyiNt6qwMDRzSV3E1Cc1WcOwU65cqRU
spring.datasource.driver-class-name=org.postgresql.Driver

# -------------------------
# JPA / HIBERNATE
# -------------------------
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# -------------------------
# SWAGGER / OPENAPI
# -------------------------
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# -------------------------
# ACTUATOR
# -------------------------
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

# Explicit port for local environments (matches Docker)
server.port=8081

management.endpoints.web.cors.allowed-origin-patterns=http://localhost:*,https://*.vercel.app
management.endpoints.web.cors.allowed-methods=GET,OPTIONS
management.endpoints.web.cors.allowed-headers=*

# -------------------------
# (OPCIONAL) LOGGING
# -------------------------
logging.level.org.springframework=INFO